import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";
import LocalDateTime from "@/components/LocalDateTime";
import InvitationCard from "@/components/InvitationCard";
import { archiveExpiredParties } from "@/lib/party-lifecycle";
type PartyRow={id:string;title:string|null;start_time:Date;end_time:Date|null;difficulty_stage:number;is_practice:boolean;leader_username:string;encounters:string;members:number;party_size:number;need_physical:number;need_magical:number;need_support:number;assigned_physical:number;assigned_magical:number;assigned_support:number;composition_restricted:boolean};
type Inv={id:string;start_time:Date;leader:string;encounters:string};
export default async function Home(){
  const user=await requireUser();await archiveExpiredParties();
  const invitations=await query<Inv>(`SELECT p.id,p.start_time,COALESCE(u.display_name,u.username) leader,string_agg(DISTINCT e.code, ', ' ORDER BY e.code) encounters FROM party_members pm JOIN parties p ON p.id=pm.party_id JOIN users u ON u.id=p.leader_id JOIN party_encounters pe ON pe.party_id=p.id JOIN encounters e ON e.id=pe.encounter_id WHERE pm.user_id=$1 AND pm.status='INVITED' AND p.status IN ('OPEN','FULL') GROUP BY p.id,u.display_name,u.username ORDER BY p.start_time`,[user.id]);
  const parties=await query<PartyRow>(`SELECT p.id,p.title,p.start_time,p.end_time,p.difficulty_stage,p.is_practice,u.username leader_username,r.party_size,p.need_physical,p.need_magical,p.need_support,p.composition_restricted,string_agg(DISTINCT e.code, ', ' ORDER BY e.code) encounters,count(DISTINCT pm.user_id)::int members,count(DISTINCT pm.user_id) FILTER (WHERE c.damage_type='PHYSICAL' AND c.role IN ('DPS','FLEX'))::int assigned_physical,count(DISTINCT pm.user_id) FILTER (WHERE c.damage_type='MAGICAL' AND c.role IN ('DPS','FLEX'))::int assigned_magical,count(DISTINCT pm.user_id) FILTER (WHERE c.role='SUPPORT')::int assigned_support FROM parties p JOIN raids r ON r.id=p.raid_id JOIN users u ON u.id=p.leader_id JOIN party_encounters pe ON pe.party_id=p.id JOIN encounters e ON e.id=pe.encounter_id LEFT JOIN party_members pm ON pm.party_id=p.id AND pm.status='ACCEPTED' LEFT JOIN characters ch ON ch.id=pm.character_id LEFT JOIN classes c ON c.id=ch.class_id WHERE p.status IN ('OPEN','FULL') GROUP BY p.id,r.party_size,u.username ORDER BY p.start_time ASC LIMIT 50`);
  return <main><section className="hero"><p className="muted">DOOM APORIA • GUILD ONLY</p><h1>Find the raid.<br/>Not the timezone.</h1><p>Welcome {user.display_name??user.username}. Browse all open parties here, publish your availability, or create a party and let the matcher find compatible guild members.</p><div className="row"><Link className="btn primary" href="/parties/new">Create Doom party</Link><Link className="btn" href="/availability">Set availability</Link><Link className="btn" href="/my-parties">My parties</Link></div></section>{invitations.rows.length>0&&<><h2>Invitations</h2><div className="grid">{invitations.rows.map(i=><InvitationCard key={i.id} party={{id:i.id,leader:i.leader,encounters:i.encounters,start:new Date(i.start_time).toISOString()}}/>)}</div></>}<h2 className="section-title">Open parties</h2><div className="grid">{parties.rows.length===0&&<div className="card muted">No open parties yet. Create one or publish your availability.</div>}{parties.rows.map(p=>{const remP=Math.max(0,p.need_physical-p.assigned_physical);const remM=Math.max(0,p.need_magical-p.assigned_magical);const remS=Math.max(0,p.need_support-p.assigned_support);return <article className="card stack" key={p.id}><div className="row between"><strong>{p.title||"Doom Aporia"}</strong><span className="pill">{p.is_practice?"Practice":"Clear"}</span></div><div><div className="muted">Run</div><strong>{p.encounters}</strong> • Stage {p.difficulty_stage}</div><div><div className="muted">When</div><LocalDateTime iso={new Date(p.start_time).toISOString()}/>{p.end_time&&<> → <LocalDateTime iso={new Date(p.end_time).toISOString()} timeOnly/></>}</div><div className="row"><span className="pill">Created by @{p.leader_username}</span><span className="pill">{p.members}/{p.party_size} joined</span><span className="pill">{p.composition_restricted?'Role matching on':'Any role allowed'}</span></div><div className="need">Remaining request: {remP} Physical · {remM} Magical · {remS} Support</div><Link className="btn" href={`/parties/${p.id}`}>View party</Link></article>})}</div></main>;
}
