"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
type E={id:string;code:string;name:string};
type Initial={title?:string;encounters:string[];startTime:string;endTime?:string|null;difficultyStage:number;isPractice:boolean;practiceEncounterId?:string|null;needPhysical:number;needMagical:number;needSupport:number};
export default function PartyForm({encounters,partyId,initial}:{encounters:E[];partyId?:string;initial?:Initial}){
  const router=useRouter();
  const allIds=useMemo(()=>encounters.map(e=>e.id),[encounters]);
  const [selected,setSelected]=useState<string[]>(initial?.encounters??allIds);
  const [practice,setPractice]=useState(initial?.isPractice??false);
  const [range,setRange]=useState(Boolean(initial?.endTime));
  const [msg,setMsg]=useState("");
  const fullRun=selected.length===allIds.length && allIds.every(id=>selected.includes(id));
  function toggleEncounter(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
  function toggleFull(){setSelected(fullRun?[]:allIds);}
  const localValue=(iso?:string|null)=>{if(!iso)return "";const d=new Date(iso);const z=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;};
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected.length){setMsg('Select at least one fight.');return;}const f=new FormData(e.currentTarget);const start=new Date(String(f.get('start')));const end=range?new Date(String(f.get('end'))):null;const body={title:String(f.get('title')||''),encounters:selected,startTime:start.toISOString(),endTime:end?.toISOString()??null,difficultyStage:Number(f.get('stage')),isPractice:practice,practiceEncounterId:practice?String(f.get('practiceEncounter')):null,needPhysical:Number(f.get('physical')),needMagical:Number(f.get('magical')),needSupport:Number(f.get('support'))};setMsg(partyId?'Saving…':'Creating…');const r=await fetch(partyId?`/api/parties/${partyId}`:'/api/parties',{method:partyId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(r.ok)router.push(partyId?`/parties/${partyId}`:`/parties/${j.id}`);else setMsg(j.issues?.[0]?.message??j.error??'Could not save party');}
  return <form onSubmit={submit} className="card form stack"><label>Optional title<input name="title" maxLength={80} defaultValue={initial?.title??''} placeholder="Saturday Doom full run"/></label><div><div className="muted">Run</div><div className="checks"><label><input type="checkbox" checked={fullRun} onChange={toggleFull}/><strong>Full Run</strong></label>{encounters.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggleEncounter(x.id)}/>{x.code}</label>)}</div></div><label>Difficulty stage<input name="stage" type="number" min="1" max="99" defaultValue={initial?.difficultyStage??1} required/></label><div className="checks"><label><input type="checkbox" checked={practice} onChange={e=>setPractice(e.target.checked)}/>Practice group</label>{practice&&<select name="practiceEncounter" defaultValue={initial?.practiceEncounterId??selected[0]??encounters[0]?.id}>{encounters.filter(x=>selected.includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select>}</div><div className="checks"><label><input type="checkbox" checked={range} onChange={e=>setRange(e.target.checked)}/>Use a time range</label></div><label>{range?'Available from':'Start time'}<input name="start" type="datetime-local" defaultValue={localValue(initial?.startTime)} required/></label>{range&&<label>Available until<input name="end" type="datetime-local" defaultValue={localValue(initial?.endTime)} required/></label>}<h3>What the party needs</h3><div className="grid"><label>Physical DPS<input name="physical" type="number" min="0" max="8" defaultValue={initial?.needPhysical??0}/></label><label>Magical DPS<input name="magical" type="number" min="0" max="8" defaultValue={initial?.needMagical??0}/></label><label>Support<input name="support" type="number" min="0" max="8" defaultValue={initial?.needSupport??0}/></label></div><div className="row"><button className="btn primary">{partyId?'Save changes':'Create party'}</button><span className="error">{msg}</span></div></form>;
}
