import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";
import LocalDateTime from "@/components/LocalDateTime";
import { archiveExpiredParties } from "@/lib/party-lifecycle";
type Row={id:string;title:string|null;start_time:Date;end_time:Date|null;difficulty_stage:number;is_practice:boolean;encounters:string;status:string;leader_id:string;leader_username:string;member_status:string|null;character_name:string|null;abbreviation:string|null};
export default async function MyParties(){
  const user=await requireUser();await archiveExpiredParties();
  const rows=await query<Row>(`SELECT p.id,p.title,p.start_time,p.end_time,p.difficulty_stage,p.is_practice,p.status,p.leader_id,u.username leader_username,string_agg(DISTINCT e.code, ', ' ORDER BY e.code) encounters,mine.status member_status,ch.character_name,c.abbreviation FROM parties p JOIN users u ON u.id=p.leader_id JOIN party_encounters pe ON pe.party_id=p.id JOIN encounters e ON e.id=pe.encounter_id LEFT JOIN party_members mine ON mine.party_id=p.id AND mine.user_id=$1 LEFT JOIN characters ch ON ch.id=mine.character_id LEFT JOIN classes c ON c.id=ch.class_id WHERE p.status IN ('OPEN','FULL') AND (p.leader_id=$1 OR mine.status IN ('ACCEPTED','INVITED')) GROUP BY p.id,u.username,mine.status,ch.character_name,c.abbreviation ORDER BY p.start_time ASC`,[user.id]);
  const created=rows.rows.filter(r=>r.leader_id===user.id);const joined=rows.rows.filter(r=>r.leader_id!==user.id&&r.member_status==='ACCEPTED');const invited=rows.rows.filter(r=>r.leader_id!==user.id&&r.member_status==='INVITED');
  const section=(title:string,items:Row[],empty:string)=><><h2 className="section-title">{title}</h2><div className="grid">{items.length===0&&<div className="card muted">{empty}</div>}{items.map(p=><article className="card stack" key={p.id}><div className="row between"><strong>{p.title||'Doom Aporia'}</strong><span className="pill">{p.leader_id===user.id?'Leader':p.member_status==='INVITED'?'Invited':'Joined'}</span></div><span>{p.encounters} · Stage {p.difficulty_stage} · {p.is_practice?'Practice':'Clear'}</span><div><LocalDateTime iso={new Date(p.start_time).toISOString()}/>{p.end_time&&<> → <LocalDateTime iso={new Date(p.end_time).toISOString()} timeOnly/></>}</div><span className="muted">Created by @{p.leader_username}</span>{p.member_status==='ACCEPTED'&&<span>Your character: <strong>{p.character_name?`${p.character_name}${p.abbreviation?` — ${p.abbreviation}`:''}`:'Not selected yet'}</strong></span>}<Link className={`btn ${p.member_status==='INVITED'?'primary':''}`} href={`/parties/${p.id}`}>{p.leader_id===user.id?'Manage party':p.member_status==='INVITED'?'Review invitation':'View party'}</Link></article>)}</div></>;
  return <main><div className="row between"><div><h1>My parties</h1><p className="muted">Everything you created, joined, or were invited to.</p></div><Link className="btn primary" href="/parties/new">+ Create Party</Link></div>{section('Created by me',created,'You do not currently have any open parties you created.')}{section('Joined',joined,'You have not joined any upcoming parties.')}{section('Invitations',invited,'You have no pending invitations.')}</main>;
}
